function obj = loadobj(S)
obj = SampledProcess('tStart',...
   S.tStart,...
   'Fs',S.Fs,...
   'values',S.values_,...
   'offset',S.offset_,...
   'window',S.window_,...
   'labels',S.labels,...
   'info',S.info,...
   'quality',S.quality);
obj.window = S.window;
obj.offset = S.offset;
